Vagrant.configure("2") do |config|
  config.vm.box = "base"

  config.vm.define "dhcp" do |dhcp|
    dhcp.vm.box = "kingchappers/windows2016EvalDHCP" 
    dhcp.vm.network "private_network", ip: "192.168.1.11"
  end 

  config.vm.define "dns" do |dns|
    dns.vm.box = "kingchappers/windowsServer2016EvalDNS"
    dns.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "dc" do |dc|
    dc.vm.box = "kingchappers/windowsServer2016EvalDomainController"
    dc.vm.network "private_network", type: "dhcp"
  end

end
