Vagrant.configure("2") do |config|
  config.vm.box = "base"

  config.vm.define "dhcp" do |dhcp|
    dhcp.vm.box = "kingchappers/windows2016EvalDHCP" 
  end 

  config.vm.define "dns" do |dns|
    dns.vm.box = "kingchappers/windowsServer2016EvalDNS"
  end

  config.vm.define "dc" do |dc|
    dc.vm.box = "kingchappers/windowsServer2016EvalDomainController"
  end

end
