# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kingchappers/pfsense"
  #Default username & Password for pfsense = admin/pfsense
  config.vm.network :forwarded_port, guest: 443, host: 1234
end
