# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kingchappers/pfsense"
  config.vm.network :forwarded_port, guest: 80, host: 1234
  config.vm.network :forwarded_port, guest: 443, host: 1235
end
